---
- hosts: jenkins-slave
  become: true 
  tasks: 
  - name: update ubuntu repo and cache 
    apt: 
      update_cache: yes 
      fource_apt_get: yes 
      cache_valid_time: 3600 

  - name: install java 
    apt: 
      name: openjdk-11-jre
      state: present

  - name: download maven packages 
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz
      dest: /opt

  - name: extract maven packages 
    unarchive:
      src: /opt/apache-maven-3.9.2-bin.tar.gz
      dest: /opt 
      remote_src: yes

  - name: Add Maven path to .bashrc
    lineinfile:
      path: ~/.bashrc
      line: 'export PATH=$PATH:/opt/apache-maven-3.9.2/bin'
      create: yes
      insertafter: EOF

  - name: Reload .bashrc
    command: source ~/.bashrc

---
- name: Example Maven Usage
  hosts: your_target_hosts
  become: yes  # This enables privilege escalation, usually to root

  tasks:
    - name: Run Maven clean install
      command: mvn clean install
      args:
        chdir: /path/to/your/maven/project  